HappyGo/urls.py
from django.contrib import admin
from django.urls import path,include
from inventory import urls as inventory_urls
# app_name = 'HappyGo'
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include("inventory.urls", namespace="inventory")),
    path('products/', include('products.urls')),
]



# Your url patterns ...

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
# products/urls.py
from django.urls import path
from .views import view_cart, add_to_cart, remove_from_cart
from . import views
app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('user/', views.user_view, name='user_view'),
    path('logout/', views.user_logout, name='logout'),


    # Shopping cart
    path('cart/', view_cart, name='view_cart'),
    path('cart/add/<str:upc>/', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart/update/',views.edit_to_cart, name='edit_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_details'),


    # User portal
    path('profile/',views.profile_view, name='profile_view'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('address/', views.address_view, name='address_view'),
    path('address_edit/', views.address_edit, name='address_edit'),
    path('orders/', views.orders_view, name='orders_view'),


    # Category
    path('dairy_view/', views.dairy_view, name='dairy_view'),
    path('meat_view/', views.meat_view, name='meat_view'),
    path('fruit_view/', views.fruit_view, name='fruit_view'),
    path('bakery_view/', views.bakery_view, name='bakery_view'),

    # Item Search
    path('item_search/', views.item_search, name='item_search'),

    # Products
    path('product_detail/<str:upc>', views.product_detail, name='product_detail')


]

inventory/models.py
from datetime import timezone, datetime

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
from django.db import models
from django.utils.translation import gettext_lazy as _  # for translating
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from django.db import models
from django.contrib.auth.models import AbstractBaseUser


# use for store hierarchy data


class Category(models.Model):
    """
    Inventory category table implimented with MPTT
    """
    name = models.CharField(
        max_length=100,
        null=False,
        unique=False,
        blank=False,
        verbose_name=_("category name"),
        help_text=_("format:required,max-100")
    )



    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("product category")
        verbose_name_plural = _("product categories")



class Product(models.Model):
    """
    Product details table
    """
    upc = models.CharField(
        max_length=50,
        unique=True,
        null=True,
        blank=False,
        verbose_name=_("product upc"),
        help_text=_("format:required,unique")
    )

    name = models.CharField(
        max_length=100,
        null=False,
        unique=False,
        blank=False,
        verbose_name=_("product name"),
        help_text=_("format:required,max-100")
    )
    description = models.TextField(
        max_length=255,
        null=False,
        blank=False,
        verbose_name=_("product description"),
        help_text=_("format:required,max-100"),
    )
    product_type_id = models.ForeignKey(
        "ProductType",
        to_field="id",
        on_delete=models.CASCADE,
        verbose_name=_("product type"),
        null=True,
    )
    is_active = models.BooleanField(
        default=True,
        unique=False,
        blank=False,
        verbose_name=("Product visibility"),
        help_text=_("format:true=product visible"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("created at"),
        help_text=_("format:Y-m-d H:M:S")
    )

    weight = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=False,
        blank=False,
        default=0,
        verbose_name=_("weight of product")
    )

    media_id = models.ForeignKey(
        "Media",
        to_field="id",
        on_delete=models.CASCADE,
        verbose_name=_("pictures"),
        null=True,
        blank=True,

    )

    brand_id = models.ForeignKey(
        "Brand",
        to_field="id",
        on_delete=models.CASCADE,
        verbose_name=_("brand"),
        null=True,

    )



class ProductType(models.Model):
    """
    Product type table
    """

    name = models.CharField(
        max_length=255,
        unique=True,
        blank=False,
        verbose_name=_("type of product"),
        help_text=_("format:product,unique,max-255"),
    )

    category_id = models.ForeignKey(
        "Category",
        to_field="id",
        default=0,
        on_delete=models.CASCADE)




class Brand(models.Model):
    """
    Product brands table
    """
    name = models.CharField(
        max_length=30,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("brand name"),
        help_text=_("format:required,unique,max-255"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("created at"),
        help_text=_("format:Y-m-d H:M:S"),
    )

class Location(models.Model):
    """
    Product stocks location table
    """

    location = models.CharField(
        max_length=20,
        verbose_name=_("location"),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Location availability"),
        help_text=_("format:true=product visible")
    )

class Media(models.Model):
    """
    Product media (picture, video, etc.)
    """
    upc = models.ForeignKey(
        "ProductInventory",
        on_delete=models.SET_NULL,
        null=True,
    )

    url = models.URLField(
        max_length=100,
        verbose_name=_("url")
    )



class ProductInventory(models.Model):
    """
    Product inventory table
    """

    product_id = models.OneToOneField(
        "Product",
        to_field="id",
        related_name="product_id",
        verbose_name=_("product id"),
        on_delete=models.PROTECT,
        default=1,
        unique=True,
    )
    product_name = models.ForeignKey(
        "Product",
        to_field="id",
        related_name="product_name",
        verbose_name=_("product name"),
        on_delete=models.PROTECT,
        default=1,
    )

    product_type_id = models.ForeignKey(
        "ProductType",
        to_field="id",
        related_name="product_type",
        on_delete=models.PROTECT,
        blank=False,
        verbose_name=_("product type"),
        default=1,

    )


    brand_id = models.ForeignKey(
        "Brand",
        to_field="id",
        related_name="brand",
        verbose_name=_("brand id"),
        on_delete=models.PROTECT,
        default=1,
    )
    upc = models.CharField(
        max_length=12,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("universal product code"),
        help_text=_("format:required,unique,max-12")
        , default=1,
    )
    #
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("product visibility_in"),
        help_text=_("format:true=product visible")
    )

    retail_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        unique=False,
        null=True,
        blank=True,
        verbose_name=_("recommended price"),
        default=0,
        help_text=_("format:maximum price 999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be greater than or equal to 999.99")
            }
        }

    )

    store_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        unique=False,
        null=True,
        default=0,
        blank=True,
        verbose_name=_("recommended price"),
        help_text=_("format:maximum price 999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be greater than or equal to 999.99")
            }
        }

    )

    weight = models.FloatField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("product weight"),
        default=0,
    )

    current_datetime = datetime.now()
    formatted_datetime = current_datetime.strftime("%Y-%m-%d %H:%M:%S")



    update_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("last update at"),
        help_text=_("format:Y-m-d H:M:S")
    )

    total = models.IntegerField(
        default=0,
        editable=True,
        blank=False,
        verbose_name=_("Total")

    )

    location = models.ForeignKey(
        "Location",to_field="id",
        on_delete=models.CASCADE,
        null=True,
    )


#======================== user ===================

class AdminUserManager(BaseUserManager):
    def create_user(self, user_name, password=None, **extra_fields):

        if not user_name:
            raise ValueError(_('The Username must be set'))
        user = self.model(user_name=user_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_name, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(user_name, password, **extra_fields)

class AdminUser(AbstractBaseUser):
    user_name = models.CharField(max_length=30, unique=True, verbose_name=_("User name"))
    password = models.CharField(max_length=100, verbose_name=_("Password"))
    admin_email = models.EmailField(max_length=254, unique=True, verbose_name=_("Email address"))
    is_admin = models.BooleanField(default=False, verbose_name=_("admin user"))
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    USERNAME_FIELD = 'user_name'
    REQUIRED_FIELDS = ['email']

    objects = AdminUserManager()

    def __str__(self):
        return self.user_name

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin


class User(models.Model):
    user_name = models.CharField(
        unique=True,
        max_length=30,
        null=False,
        blank=False,
        verbose_name=_("User name")
    )

    password = models.CharField(
        max_length=20,
        null=False,
        blank=False,
        verbose_name=_("password")
    )

    user_email = models.EmailField(
        max_length=20,
        null=False,
        blank=False,
        unique=True,
        verbose_name=_("email address")
    )

products/models.py
from django.db import models
from django.conf import settings
from inventory.models import Product, ProductInventory,AdminUser,AdminUserManager


# Create your models here.
class ShoppingCart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shopping_cart')
    created_at = models.DateTimeField(auto_now_add=True)

class ShoppingCartItem(models.Model):
    cart = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(ProductInventory, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


class Profiles(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name='profile' )
    full_name = models.CharField(max_length=60, blank=True,null=True)
    street = models.CharField(max_length=60, blank=True,null=True)
    city = models.CharField(max_length=60, blank=True,null=True)
    state = models.CharField(max_length=60, blank=True,null=True)
    zipcode = models.CharField(max_length=5, blank=True,null=True)
    telephone = models.CharField(max_length=15, blank=True,null=True)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shipping_address = models.ForeignKey(Profiles, on_delete=models.DO_NOTHING, null=True)
    total_price = models.DecimalField(max_digits=6, decimal_places=2,default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    ship_status = models.BooleanField(default=False)
    tracking_number = models.CharField(max_length=10, blank=True,null=True,default=None)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(ProductInventory, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)  # price at the time of purchase
    items_price = models.DecimalField(max_digits=6, decimal_places=2, default=0.0)

products/forms.py
from django import forms
from django import forms
from .models import Profiles

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profiles
        fields = ['full_name', 'street', 'city', 'state', 'zipcode', 'telephone']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}),
            'street': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Street'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}),
            'state': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'State'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'telephone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telephone'}),
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

products/templates/address.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/user_portal.css' %}">
    <style>
        .left_nav {
            float: left;
            position: relative;
            left: 30px;
            height: 421px;
            width: 190px;

        {#background-color: rgba(0, 0, 205, 0.3);#}
            /*background-color: rgba(0, 0, 0, 0.3);*/
            /* rgba(65, 105, 250, 0.3);*/
        }

        .left_nav ul li {
            height: 36px;
            line-height: 46px;
            white-space: nowrap;
        }

        .left_nav ul li a {
            color: black;
            font-size: 18px;
            margin-left: -5px;
        }

        .left_nav ul li a span {
            float: right;
        }

        .left_nav ul li a:hover {
            color: #00a4ff;
        }


        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            color: white;
            position: relative;
            right: -290px;
        }

        .profile {
            border: solid 1px black;
            position: absolute;
            display: block;
            width: 380px;
            height: 450px;
            left: 500px;
        }

        .profile form {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }

        .form-row {
            display: flex;
            margin-bottom: 10px;
            align-items: center;
            padding: 20px 30px;
        }

        .form-row label {
            width: 150px;
            margin-right: 10px;
        }

        .form-row input {
            flex-grow: 1;
        }


    </style>

    <meta charset="UTF-8">

    {% block title %}
        <h2>Manage your Profiles</h2>
    {% endblock %}
</head>
<body>


<p class="nav">
<ul class="nav_head">
    <li><a href="{% url 'products:index' %}">Home</a></li>
    <li><a href="#">Dairy</a></li>
    <li><a href="#">Fresh</a></li>
    <li><a href="#">Bakery</a></li>
    <li><a href="#">Meat</a></li>
    <li><a href="/products/cart">Shopping Cart</a></li>
    <li style="float: right;color: cadetblue">
        <a href="/products/profile">My Account</a></li>
</ul>
</p>
{% block content %}
    <h3>My Account</h3>
    <div class="left_nav">
        <ul>
            <li><a href="/products/profile">Profiles &nbsp&nbsp<span>&gt</span></a></li>

            <li><a href="/products/address">Address &nbsp<span>&gt</span></a></li>

            <li><a href="/products/orders">Order &nbsp&nbsp<span>&gt</span></a></li>

            <li><a href="/products/logout">Log out</a></li>
        </ul>
    </div>

    <div class="profile">
        <form method="post" action="{% url 'products:address_edit' %}">
            {% csrf_token %}
            <div class="form-row">
                <label for="full_name">Full Name</label>
                <input type="text" name='full_name' value="{{ full_name }}" placeholder="full name">
            </div>
            <div class="form-row">
                <label for="street">Street</label>
                <input type="text" name='street' value="{{ street }}" placeholder=" street">
            </div>
            <div class="form-row">
                <label for="city">City</label>
                <input type="text" name='city' value="{{ city }}" placeholder=" city">
            </div>
             <div class="form-row">
                <label for="State">City</label>
                <input type="text" name='state' value="{{ state }}" placeholder=" state">
            </div>
            <div class="form-row">
                <label for="zipcode">Zip Code</label>
                <input type="text" name='zipcode' value="{{ zipcode}}" placeholder=" zip code">
            </div>
             <div class="form-row">
                <label for="telephone">Telephone</label>
                <input type="text" name='telephone' value="{{telephone}}" placeholder=" Telephone">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

{% endblock content %}
</body>
</html>

products/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Happy Go</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="header w">
    <div class="logo">
        <img src="{% static 'images/logo.png' %}" alt="">
    </div>
    <div class="nav">
        <ul>
            <li><a href="/products/">Home</a></li>
            <li><a href="/products/dairy_view">Dairy</a></li>
            <li><a href="/products/fruit_view">Fresh</a></li>
            <li><a href="/products/bakery_view">Bakery</a></li>
            <li><a href="/products/meat_view">Meat</a></li>
            <li><a href="/products/cart">Shopping Cart</a></li>
        </ul>
    </div>
    <div class="search">
        <form action="{% url 'products:item_search' %}" method="post">
            {% csrf_token %}
            <input type="text" name="item_search" placeholder="Enter here">
            <button type="submit" class="search_button"></button>
        </form>
    </div>
    <div class="user">
        {% if request.user.is_authenticated %}
            <span>Welcome, {{ request.user.username }}</span>
            <a href="/products/user">My Account</a>
        {% else %}
            <a href="/products/login">Login</a>
        {% endif %}
    </div>

</div>
<div class="banner">
    <div class="w">
        <div class="subnav">
            <ul>
                <li><a href="/products/fruit_view">Fruit <span>&gt</span></a></li>
                <li><a href="/products/dairy_view">Dairy <span>&gt</span></a></li>
                <li><a href="/products/bakery_view">Bakery <span>&gt</span></a></li>
                <li><a href="/products/meat_view">Seafood <span>&gt</span></a></li>
                <li><a href="/products/meat_view">Meat <span>&gt</span></a></li>
            </ul>
        </div>

    </div>
</div>
<div class="suggest w">
    <div class="boutique"><h4>&nbsp&nbsp On sale ! Time Limited</h4></div>
    <div class="course">
        <ul>
            <li>product</li>
            <li>product</li>
            <li>product</li>
            <li>product</li>
            <li>product</li>
            <li>product</li>
        </ul>
    </div>
    <div class="r_button"><a href="#">Modify</a></div>
</div>
<!--content-->
<div class="box w">
    <div class="box-hd">
        <h3>Recommend</h3>
        <a href="#">View All</a>
    </div>
    <div class="box-bd clearfix">
        <form action="" method="post">
            {% csrf_token %}
            <ul>
                {% for invent_obj in  inventory_list %}
                    {% with invent_obj.media_set.first as media %}
                        <li>
                            {% if media %}
                                <img src="{{ MEDIA_URL }}{{ media.url }}"
                                     alt="Image for {{ invent_obj.product_obj.name }}">

                            {% endif %}
                            <a href="{% url 'products:product_detail' invent_obj.upc %}" >
                                <h4>{{ invent_obj.product_obj.name }}</h4>
                            </a>
                            <button id="add_to_cart" type="button"
                                    onclick="location.href='{% url 'products:add_to_cart' invent_obj.upc %}'">ADD TO
                                CART
                            </button>
                        </li>
                    {% endwith %}
                {% endfor %}
            </ul>
        </form>
    </div>
</div>


<div class="footer">
    <div class="w">
        <div class="copyright">
            <img src="images/logo.png" alt="">
            <p>CIT693 Course Project Peng Ouyang</p>
            <a href="#">NAU</a>
        </div>
        <div class="links">

            <dl>
                <dt>Links</dt>
                <dd><a href="https://nau.edu">NAU</a></dd>

            </dl>
        </div>
    </div>
</div>
</body>
</html>

products/templates/orders.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/user_portal.css' %}">
    <style>
        .left_nav {
            float: left;
            position: relative;
            left: 30px;
            height: 421px;
            width: 190px;

        {#background-color: rgba(0, 0, 205, 0.3);#}
            /*background-color: rgba(0, 0, 0, 0.3);*/
            /* rgba(65, 105, 250, 0.3);*/
        }

        .left_nav ul li {
            height: 36px;
            line-height: 46px;
            white-space: nowrap;
        }

        .left_nav ul li a {
            color: black;
            font-size: 18px;
            margin-left: -5px;
        }

        .left_nav ul li a span {
            float: right;
        }

        .left_nav ul li a:hover {
            color: #00a4ff;
        }


        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            color: white;
            position: relative;
            right: -290px;
        }

        .profile {
            position: absolute;
            display: block;
            width: 580px;
            height: 380px;
            left: 400px;
        }

        .profile form {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }

        .form-row {
            display: flex;
            margin-bottom: 10px;
            align-items: center;
            padding: 20px 30px;
        }

        .form-row label {
            width: 150px;
            margin-right: 10px;
        }

        .form-row input {
            flex-grow: 1;
        }

        .product_list_table {
            table-layout: fixed;
            width: 100%;
        }

        table {
            border-collapse: collapse;
            border: 1px solid #bbccdd;
        }

        th, td {
            display: table-cell;
            text-align: center;
            padding: 0 8px;
            border: 1px solid #bbccdd;
        }
        #product_list_form{
            height: 400px;
            width: 880px;
            overflow-y: auto;
        }

    </style>

    <meta charset="UTF-8">

    {% block title %}
        <h2>Manage your Profiles</h2>
    {% endblock %}
</head>
<body>


<p class="nav">
<ul class="nav_head">
    <li><a href="{% url 'products:index' %}">Home</a></li>
    <li><a href="#">Dairy</a></li>
    <li><a href="#">Fresh</a></li>
    <li><a href="#">Bakery</a></li>
    <li><a href="#">Meat</a></li>
    <li><a href="/products/cart">Shopping Cart</a></li>
    <li style="float: right;color: cadetblue">
        <a href="/products/profile">My Account</a></li>
</ul>
</p>
{% block content %}
    <h3>My Account</h3>
    <div class="left_nav">
        <ul>
            <li><a href="/products/profile">Profiles &nbsp&nbsp<span>&gt</span></a></li>

            <li><a href="/products/address">Address &nbsp<span>&gt</span></a></li>

            <li><a href="">Order &nbsp&nbsp<span>&gt</span></a></li>

            <li><a href="/products/logout">Log out</a></li>
        </ul>
    </div>

    <div class="profile">
        <form id="product_list_form" action="{% url 'products:edit_to_cart' %}" method="post" class="product_list">
            {% csrf_token %}
            <table class="product_list_table" style="width: 800px">
                <tr id="table_row">
                    <th class="td_th">Order ID</th>
                    <th id="td_th1">Total Price</th>
                    <th class="td_th">Date</th>
                    <th class="td_th">Status</th>
                    <th class="td_th">Tracking</th>
                    <th class="td_th">Details</th>
                </tr>
                {% for order in order_list %}
                    <tr id="list_detail">
                        <td class="td_th">{{ order.id }}</td>
                        <td id="td_th2">{{ order.total_price }}</td>
                        <td class="td_th">{{ order.created_at }}</td>
                        <td class="td_th">{{ order.ship_status }}</td>
                        <td class="td_th">{{ order.tracking_number }}</td>
                        <td>
                            <a href="{% url 'products:order_details' order.id %}" class="btn btn-danger">Details</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">Your cart is empty.</td>
                    </tr>
                {% endfor %}
            </table>

        </form>
    </div>

{% endblock content %}
</body>
</html>

products/templates/shopping_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'product_list.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
        .product_list_table {
            table-layout: fixed; /* 新增固定表格布局属性 */
            width: 100%; /* 根据需要设置表格宽度 */
        }

        th, td {
            display: table-cell; /* 改变布局属性 */
            text-align: center;
            border: 1px solid #bbccdd;
            padding: 0 8px;
        }

        #td_th2 {
            width: 250px;
        }

        .td_th {
            display: inline-block;
            overflow: hidden;
            width: auto;
            max-height: 30px;
            max-width: 570px;
        }

        #item_total {
            width: 60px;
        }

        #total_price {
        {#border: solid 1px black; #} font-size: 22px;
            color: #1b1b1b;
            width: 800px;
        }

        #check_out {
            display: inline-block;
            background-color: #ff3211;
            color: #81d4fa;
            border-radius: 10px;
            height: 30px;
            width: 120px;
            font-size: 18px;
        }


    </style>

</head>

<body>

<p class="nav">
<ul class="nav_head">
    <li><a href="/products/#">Home</a></li>
    <li><a href="#">Dairy</a></li>
    <li><a href="#">Fresh</a></li>
    <li><a href="#">Bakery</a></li>
    <li><a href="#">Meat</a></li>
    <li><a href="/products/cart">Shopping Cart</a></li>
    <li style="float: right;color: cadetblue"><a href="{% url 'products:user_view' %}">My Account</a></li>
</ul>
</p>

<h2 style="text-align: center">Shopping Cart</h2>
<form id="product_list_form" action="{% url 'products:edit_to_cart' %}" method="post" class="product_list">
    {% csrf_token %}
    <table class="product_list_table" style="width: 800px">
        <tr id="table_row">
            <th class="td_th">UPC</th>
            <th id="td_th1">Product Name</th>
            <th class="td_th">Price</th>
            <th class="td_th">Quantity</th>
            <th class="td_th">Actions</th>
        </tr>
        {% for item in cart.items.all %}
            <tr id="list_detail">
                <input type="hidden" name="item_upc_{{ item.product.upc }}" value="{{ item.product.upc }}">
                <td class="td_th">{{ item.product.upc }}</td>
                <td id="td_th2">{{ item.product.product_name.name }}</td>
                <td class="td_th">{{ item.product.store_price }}</td>
               <td class="td_th">
                <input id="item_total" type="number" name="quantity_{{ item.product.upc }}" value="{{ item.quantity }}">
                </td>
                <td>
                    <button type="submit" name="action" value="modify">
                        Modify
                    </button>
                    <button><a style="text-decoration: None" href="{% url 'products:remove_from_cart' item.id %}"
                               class="btn btn-danger">Remove</a></button>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">Your cart is empty.</td>
            </tr>
        {% endfor %}
    </table>
    {% if cart.items.all %}
        <p id="total_price">
            <label for="total_price">Total Price: ${{ total_price }}</label>
            <button type="submit" name="action" value="checkout" id="check_out" class="btn">Check Out</button>
        </p>
    {% endif %}

</form>

</body>
</html>

products/templates/user_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="reset">Reset</button>
    <button type="submit">Register</button>
</form>
</body>
</html>