HappyGo/urls.py
from django.contrib import admin
from django.urls import path,include
from inventory import urls as inventory_urls
# app_name = 'HappyGo'
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include("inventory.urls", namespace="inventory")),
    path('products/', include('products.urls')),
]



# Your url patterns ...

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'inventory'

urlpatterns = [
    path('',views.home, name='home'),
    path('categories/',views.categories, name='categories'),

    # Brand
    path('add_brand/', views.add_brand,name='add_brand'),
    path('base/', views.base),
    path('brand_edit/<int:id>/', views.brand_edit,name='brand_edit'),
    path('brand_delete/<int:id>/', views.brand_delete,name='brand_delete'),

    # Media
    path('image_add/<str:upc>', views.image_add, name='image_add'),
    path('image_delete/<str:upc>/', views.image_delete, name='image_delete'),

    # Category
    path('category_add/', views.category_add, name='category_add'),
    path('category_delete/<int:id>/', views.category_delete,name='category_delete'),
    path('category_edit/<int:id>/', views.category_edit,name='category_edit'),

    # Product Type
    path('type_add/', views.type_add, name='type_add'),
    path('type_delete/<int:id>/', views.type_delete, name='type_delete'),
    path('type_edit/<int:id>/', views.type_edit, name='type_edit'),

    # Product
    path('product_add/', views.product_add, name='product_add'),
    path('product_delete/<int:id>/', views.product_delete, name='product_delete'),
    path('product_edit/<int:id>/', views.product_edit, name='product_edit'),

    # Inventory
    path('inventory_mg/', views.inventory_mg, name='inventory_mg'),
    path('inventory_edit/',views.inventory_edit, name='inventory_edit'),
    path('inventory_delete/<str:upc>/', views.inventory_delete, name='inventory_delete'),
    path('admin_page/', views.admin_page, name='admin_page'),

    # Location
    path('location_add/', views.location_add, name='location_add'),
    path('location_edit/<int:id>', views.location_edit, name='location_edit'),
    path('location_delete/<int:id>', views.location_delete, name='location_delete'),


    # Search
    path('search/', views.search, name='search'),

    # Login / log out
    path('login/',views.login_page, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('protected/', views.MyProtectedView.as_view(), name='my_protected_view'),

    # Order
    path('order_edit/', views.order_edit, name='order_edit'),

    # Item Search



]

inventory/forms.py
from django import forms
from .models import Product
from .models import ProductInventory
from .models import AdminUser,User
class ImageUploadForm(forms.Form):
    image = forms.ImageField()


# your_app/forms.py



class AdminRegistrationForm(forms.ModelForm):
    class Meta:
        model = AdminUser
        fields = ['user_name', 'admin_email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['user_name', 'user_email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['upc', 'name', 'weight', 'description', 'product_type_id', 'brand_id', 'is_active']


class ProductInventoryForm(forms.ModelForm):
    class Meta:
        model = ProductInventory
        fields = ['upc', 'retail_price', 'store_price', 'total', 'location', 'is_active']

inventory/views.py
from datetime import timedelta

from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator

from HappyGo import settings
from inventory.models import *
from django.contrib.auth import get_user_model, logout

current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
from .models import Product, ProductType, Brand, Category, ProductInventory
from .forms import ProductForm, AdminRegistrationForm, UserRegistrationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import ImageUploadForm
from .models import Media
import os
from django.conf import settings
from products.models import Order, OrderItem, Profiles


def test_page(request):
    return render(request, 'test2.html')


class MyProtectedView(LoginRequiredMixin, TemplateView):
    template_name = 'login.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def login_page(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')
        user = authenticate(request, username=user_name, password=password)

        print("-------start to login---------")
        print("Authenticate result:", user, password)

        if user is not None:
            if user.is_admin:
                login(request, user)
                print("Logged in successfully as admin")
                return redirect('inventory:inventory_mg')
            else:
                messages.error(request, 'Access denied: User is not an admin')
        else:
            messages.error(request, 'Invalid username or password')

    return render(request, 'login.html')


@login_required
def logout_view(request):
    logout(request)
    print("Logged out successfully")
    return redirect('inventory:login')


def register(request):
    if request.method == 'POST':
        form = AdminRegistrationForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data.get('user_name')
            password = form.cleaned_data.get('password')
            admin_email = form.cleaned_data.get('admin_email')

            print(user_name, password, admin_email)
            if not admin_email:
                messages.error(request, 'Admin Email cannot be empty.')
            else:
                User = get_user_model()
                User.objects.create_user(user_name=user_name,
                                         password=password,
                                         admin_email=admin_email,
                                         is_admin=True)

                messages.success(request, f'Account created for {user_name}!')
                return redirect('inventory:login')
    else:
        form = AdminRegistrationForm()

    return render(request, 'register.html', {'form': form})


@login_required
def home(request):
    order_list = Order.objects.filter(ship_status=False).order_by('created_at').all()

    content = {
        'order_list': order_list,
    }
    return render(request, "inventory_home.html", content)


@login_required
def admin_page(request):

    order_total =Order.objects.all().count()
    order_list = Order.objects.all().order_by('created_at')
    twenty_four_hours_ago = current_time - timedelta(hours=24)
    order_24 = Order.objects.filter(created_at__gte=twenty_four_hours_ago).count()
    unship_orders = Order.objects.filter(ship_status=False).count()
    shipped_orders = Order.objects.filter(ship_status=True).count()
    out_of_stock_items = ProductInventory.objects.filter(total__lt=1).count()
    content = {
        'order_list': order_list,
        'order_total':order_total,
        'order_24':order_24,
        'unship_orders':unship_orders,
        'shipped_orders':shipped_orders,
        'out_of_stock_items':out_of_stock_items

    }
    return render(request, "inventory_home.html", content)


@login_required
def categories(request):
    data = Category.objects.all()
    return render(request, "add_brand.html", {"data": data})


# =============================      Brand    =================================
@login_required
def add_brand(request):
    data_list = Brand.objects.all()
    if request.method == "GET":
        return render(request, "add_brand.html", {"data_list": data_list})
    else:
        name = request.POST.get("brand")
        Brand.objects.create(name=name)
        return render(request, "add_brand.html", {"data_list": data_list})


@login_required
def brand_edit(request, id):
    obj = Brand.objects.filter(id=id).first()

    if request.method == "GET":

        return render(request, "brand_edit.html", {"obj": obj})
    else:
        data_list = Brand.objects.all()
        name = request.POST.get("brand_name")
        if name is not None and 0 < len(name) < 30:
            obj = Brand.objects.filter(id=id).update(name=name)
            return redirect("inventory:add_brand")
        else:
            return render(request, "brand_edit.html", {"obj": obj, "error": "Invalid data"})


@login_required
def brand_delete(request, id):
    if request.method == "GET":
        brand = get_object_or_404(Brand, id=id)
        Product.objects.filter(brand_id=id).delete()
        brand.delete()
        return redirect("inventory:add_brand")
    return redirect("inventory:add_brand")


def base(request):
    return render(request, "base.html")


# =============================      Images    =================================

def image_add(request, upc):
    """
    Handle image upload for a product.
    """
    data_list = Media.objects.all()
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the uploaded image and create a Media record
            media = save_uploaded_image(request.FILES['image'], upc)
            if media:
                return HttpResponseRedirect('/inventory/inventory_mg/')
            else:
                form.add_error(None, "Error in saving image.")
    else:
        form = ImageUploadForm()

    return render(request, 'image_add.html', {'form': form, 'upc': upc, 'data_list': data_list})


def save_uploaded_image(image_file, upc):
    """
    Save an uploaded image to the media directory and create a Media record.
    """
    save_path = os.path.join(settings.MEDIA_ROOT, 'products')
    if not os.path.exists(save_path):
        os.makedirs(save_path)

    file_path = os.path.join(save_path, image_file.name)
    with open(file_path, 'wb+') as destination:
        for chunk in image_file.chunks():
            destination.write(chunk)

    # Create a Media record
    inventory_obj = ProductInventory.objects.get(upc=upc)
    try:
        media = Media.objects.create(
            upc=inventory_obj,
            url=os.path.join('products', image_file.name)
        )
        print(media.upc.upc, media.url, "save------------")
        return media
    except Exception as e:
        print(f"Error in creating media record: {e}")
        return None


@login_required
def image_delete(request, upc):
    media_obj = get_object_or_404(Media, upc=upc)
    media_obj.delete()
    return redirect("inventory:image_add")


# =============================      Category   =================================
@login_required
def category_add(request):
    data_list = Category.objects.all()
    if request.method == "GET":
        return render(request, "category_add.html", {"data_list": data_list})
    else:
        category = request.POST.get("category")
        Category.objects.create(name=category)
        return render(request, "category_add.html", {"data_list": data_list})


@login_required
def category_edit(request, id):
    obj = Category.objects.filter(id=id).first()

    if request.method == "GET":

        return render(request, "category_edit.html", {"obj": obj})
    else:
        data_list = Category.objects.all()
        name = request.POST.get("category_name")
        if name is not None and 0 < len(name) < 30:
            obj = Category.objects.filter(id=id).update(name=name)
            return redirect("inventory:category_add")
        else:
            return render(request, "category_edit.html", {"obj": obj, "error": "Invalid data"})


@login_required
def category_delete(request, id):
    if request.method == "GET":
        category = get_object_or_404(Category, id=id)
        # delete all related obj before delete obj
        ProductType.objects.filter(category_id=id).delete()

        category.delete()
        return redirect("inventory:category_add")
    return redirect("inventory:category_add")


# =============================      Product Type   =================================

@login_required
def type_add(request):
    category_list = Category.objects.all()
    type_list = ProductType.objects.all()
    content = {
        "category_list": category_list,
        "type_list": type_list
    }

    if request.method == "GET":
        return render(request, "type_add.html", content)
    else:
        name = request.POST.get("type_name")
        category_id = request.POST.get("category_id")
        category_obj = get_object_or_404(Category, id=category_id)
        if name is None or len(name) > 30:
            return render(request, "type_add.html", {"obj": None, "error": "Invalid data"})
        ProductType.objects.create(name=name, category_id=category_obj)
        return render(request, "type_add.html", content)


@login_required
def type_edit(request, id):
    product_type_obj = ProductType.objects.filter(id=id).first()
    category_id = product_type_obj.category_id.id

inventory/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'add_item.css' %}">

    <meta charset="UTF-8">

    {% block title %}

    {% endblock %}
</head>
<body>
<p class="nav">
<ul class="nav_head">
    <li><a href="/inventory/admin_page/" style="background-color:green">Home</a></li>
      <li><a href="/inventory/inventory_mg/">Inventory </a></li>
    <li><a href="/inventory/product_add">Product</a></li>
    <li><a href="/inventory/type_add/">Product Type</a></li>
    <li><a href="/inventory/add_brand">Brand</a></li>
    <li><a href="/inventory/category_add">Category</a></li>
    <li><a href="/inventory/inventory_mg/">Search</a></li>
    <li style="float: right;color: cadetblue"><a href="{% url 'inventory:logout' %}">Logout</a></li>
</ul>
</p>
{% block content %}


{% endblock content %}
</body>
</html>

inventory/templates/category_add.html
{% extends "base.html" %}
{% load static %}
{% block title %} Add a new Brand {% endblock %}
{% block content %}


    <h2>Add a Category</h2>
    <form action="" method="post" style="height: 150px">
        {% csrf_token %}

        <p>
            <lable>Category Name: <input type="text" name="category"></lable>
        </p>

        <p>
            <lable><input type="reset"></lable>

            <lable><input type="submit"></lable>
        </p>
        <div class="list">
            <table>
                <thead>
                <tr>
                    <th>Category ID</th>
                    <th>Category name</th>
                    <th>Modify/Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in data_list %}
                    <tr>
                        <td>{{ obj.id }} </td>
                        <td>{{ obj.name }}</td>
                        <td><a href="{% url 'inventory:category_edit' obj.id %}">Modify</a>
                           <a href="{% url 'inventory:category_delete' obj.id %}" class="btn btn-danger" >/Delete</a></td>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

{% endblock %}

inventory/templates/image_add.html
{% extends "base.html" %}
{% block content %}
<h2>Image Upload Page</h2>
<form method="post" enctype="multipart/form-data">
    <h3>UPC: {{ upc }}: Images Upload</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
    <div class="list">
            <table>
                <thead>
                <tr>
                    <th>UPC</th>
                    <th>URL</th>
                    <th>Modify/Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in data_list %}
                    <tr>
                        <td>{{ obj.upc.upc }} </td>
                        <td>{{ obj.url }}</td>
                        <td><a href="{% url 'inventory:image_add' obj.upc %}">Modify</a>
                            <a href="{% url 'inventory:image_delete' obj.upc %}" class="btn btn-danger">/Delete</a></td>
                        </td>
                        <td>{{ obj.created_at }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
</form>


{% endblock %}

inventory/templates/location_add.html
{% extends "base.html" %}
{% load static %}
{% block title %} Add a new Brand {% endblock %}
{% block content %}


    <h2>Location Management</h2>
    <form action="" method="post" style="height: 150px">
        {% csrf_token %}

        <p>
            <lable>Location Name: <input type="text" name="location"></lable>
        </p>
        <p id="is_active">
            <label>Is_Active: </label> &nbsp&nbsp Active <input id="active" type="radio" name="is_active" value="True">
            Inactive<input type="radio" name="is_active" value="False">
        </p>
        <p>
            <lable><input type="reset"></lable>

            <lable><input type="submit"></lable>
        </p>
        <div class="list">
            <table>
                <thead>
                <tr>
                    <th>Location ID</th>
                    <th>Location</th>
                    <th>Is active</th>
                    <th>Modify/Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in data_list %}
                    <tr>
                        <td>{{ obj.id }} </td>
                        <td>{{ obj.location }}</td>
                        <td>{{ obj.is_active }}</td>
                        <td><a href="{% url 'inventory:location_edit' obj.id %}">Modify</a>
                            <a href="{% url 'inventory:location_delete' obj.id %}" class="btn btn-danger">/Delete</a></td>
                        </td>
                        <td>{{ obj.created_at }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

{% endblock %}

inventory/templates/location_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Location edit</h2>
</body>
</html>

inventory/templates/product_add.html
{% extends 'base.html' %}
{% block title %}
    <h2>Add Product</h2>
{% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'product_css.css' %}">
    <div class="input_page">
        <form class="main_panel" action="" method="post">
            {% csrf_token %}
            <p id="form_header">
                <label for="">Add New Product</label>
            </p>
            <p>
                <label>UPC: <input type="text" name="upc" id="upc"></label>
            </p>
            <p>

                <label class="sel1">Product type:</label>
                <select class="product_type" name="product_type_id" id="product_type">
                    {% for category in category_list %}
                        <optgroup label="{{ category.name }}">
                            {% for type_obj in type_list %}
                                {% if type_obj.category_id.id == category.id %}
                                    <option value="{{ type_obj.id }}">{{ type_obj.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </optgroup>
                    {% endfor %}
                </select>

            </p>
            <p>
                <label>Name: <input type="text" name="name"></label>
            </p>
            <p>
                <label class="sel">Brand:</label>
                <select class="form-control" name="brand_id" id="brand_id">
                    {% for item in brand_list %}
                        <option value={{ item.id }}>{{ item.name }}</option>
                    {% endfor %}
                </select>
            </p>
            <p>
                <label>Weight: <input type="text" name="weight"></label>
            </p>
            <p id="is_active">
                <label>Is_Active: </label> &nbsp&nbsp Active <input id="active" type="radio" name="is_active" value="True">
                Inactive<input type="radio"  name="is_active" value="False">
            </p>
            <p id="description">
                <label id="desc_label">Description:</label> <textarea type="text" name="description" cols="30px"
                                                                      rows="8px"> </textarea>
            </p>

{#            <p>#}
{#                <label>Total: <input type="number" name=i"total" id="total"></label>#}
{#            </p>#}
            <p>
                <label><input type="reset"></label>

                <label><input type="submit"></label>
            </p>
        </form>
    </div>

    <form class="product_list_form" action="" method="post">
        {% csrf_token %}
        <table class="product_list" style="width: auto">
            <tr>
                <th>id</th>
                <th>UPC</th>
                <th>Name</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Weight(Kg)</th>
                <th>Description</th>
                <th>created at</th>
                <th>Is Active</th>
                <th>Modify/Delete</th>
            </tr>
            {% for obj in product_list %}
                {% with inventory_obj=inventory_list.obj.id %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.upc }}</td>
                        <td style="display:inline-block;overflow:hidden;max-height: 90px">
                            {{ obj.name }}</td>
                        <td>{{ obj.product_type_id.name }}</td>
                        <td>{{ obj.brand_id.name }}</td>
                        <td>{{ obj.weight }}</td>
                        <td style="display:inline-block;overflow:hidden;max-height: 90px">
                            {{ obj.description }}</td>
                        <td>{{ obj.created_at }}</td>
                        <td>{{ obj.is_active }}</td>
                        <td><a href="{% url 'inventory:product_edit' obj.id%}" class="btn btn-primary">Modify</a>
                            <a href="{% url 'inventory:product_delete' obj.id%}" class="btn btn-danger">/Delete</a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
        </table>
    </form>


{% endblock %}

inventory/templates/product_edit.html
{% extends 'base.html' %}
{% block title %}
    <h2>Edit Product Info</h2>
{% endblock %}

{% block content %}
       {% load static %}
    <link rel="stylesheet" href="{% static 'product_css.css' %}">
    <div class="input_page">
        <form class="main_panel" action="" method="post">
            {% csrf_token %}
            <p id="form_header">
                <label for="">Edit Product Info</label>
            </p>
            <p>
                <label>UPC: <input type="text" name="upc" id="upc" value="{{ product.upc }}"></label>
            </p>
            <p>

                <label class="sel1">Product type:</label>
                <select class="product_type" name="product_type_id" id="product_type">
                    {% for category in category_list %}
                        <optgroup label="{{ category.name }}">
                            {% for type_obj in type_list %}
                                {% if type_obj.category_id.id == category.id %}
                                    <option value="{{ type_obj.id }}"
                                            {% if type_obj.id == product.product_type_id.id %}selected{% endif %}
                                    >{{ type_obj.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </optgroup>
                    {% endfor %}
                </select>

            </p>
            <p>
                <label>Name: <input type="text" name="name" value={{ product.name }}></label>
            </p>
            <p>
                <label class="sel">Brand:</label>
                <select class="form-control" name="brand_id" id="brand_id">
                    {% for item in brand_list %}
                        <option value={{ item.id }} {% if item.id == product.brand_id.id %}selected {% endif %}>{{ item.name }}</option>
                    {% endfor %}
                </select>
            </p>
            <p>
                <label>Weight: <input type="text" name="weight" value={{ product.weight }}></label>
            </p>
            <p id="is_active">
                <label>Is_Active: </label> &nbsp&nbsp Active <input id="active" type="radio" name="is_active" value="True"
            {% if product.is_active %}checked {% endif %}>
                Inactive<input type="radio"  name="is_active" value="False" {% if not product.is_active %}checked{% endif %}>
            </p>
            <p id="description">
                <label id="desc_label">Description:</label> <textarea  type="text" name="description"  cols="30px"
                                                                      rows="8px" >{{ product.description }}</textarea>
            </p>

{#            <p>#}
{#                <label>Total: <input type="number" name=i"total" id="total"></label>#}
{#            </p>#}
            <p>
                <label><input type="reset"></label>

                <label><input type="submit"></label>
            </p>
        </form>
    </div>

    <form class="product_list_form" action="" method="post">
        {% csrf_token %}
        <table class="product_list" style="width: auto">
            <tr>
                <th>id</th>
                <th>UPC</th>
                <th>Name</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Weight(Kg)</th>
                <th>Description</th>
                <th>Total</th>
                <th>Last Update</th>
                <th>Is Active</th>
                <th>Modify/Delete</th>
            </tr>
            {% for obj in product_list %}
                {% with inventory_obj=inventory_list.obj.id %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.upc }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.product_type_id.name }}</td>
                        <td>{{ obj.brand_id.name }}</td>
                        <td>{{ obj.weight }}</td>
                        <td>{{ obj.description }}</td>
                        <td>{{ inventory_obj.total }}</td>
                        <td>{{ obj.update_at }}</td>
                        <td>{{ obj.is_active }}</td>
                        <td><a href="{% url 'inventory:product_edit' obj.id%}" class="btn btn-primary">Modify</a>
                            <a href="{% url 'inventory:brand_delete' obj.id%}" class="btn btn-danger">/Delete</a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
        </table>
    </form>


{% endblock %}

inventory/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="reset">Reset</button>
    <button type="submit">Register</button>
</form>
</body>
</html>

inventory/templates/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'product_list_bk.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p class="nav">
<ul class="nav_head">
    <li><a href="/inventory_home" style="background-color:green">Home</a></li>
      <li><a href="/inventory/">Inventory </a></li>
    <li><a href="/inventory/product_add">Product</a></li>
    <li><a href="/inventory/image_add/">Media</a></li>
    <li><a href="/inventory/type_add/">Product Type</a></li>
    <li><a href="/inventory/add_brand">Brand</a></li>
    <li><a href="/inventory/category_add">Category</a></li>
    <li><a href="/add_report">Add </a></li>
    <li><a href="/search">Search</a></li>
    <li style="float: right;color: cadetblue"><a href="login.html">Log out</a></li>
</ul>
</p>


<div class="search-label-icon">
    <form action="" method="post">
        {% csrf_token %}
        <p class="search_bar">
            <label for=""></label>
            <select name="doc_type" id="type_select" style="width: 100px">
                {% for key,val in type_list.items %}
                    <option value="{{ key }}">{{ val }}</option>
                {% endfor %}
            </select>
            <input class="search_text" name="keyword" type="text" placeholder="Search">
            <input type="submit" id="search_button" value="Search">
        </p>
    </form>
</div>
<ul>
    <li>Book</li>
    <li>Journal</li>
    <li>magazine</li>
    <li>Thesis</li>
    <li>Technical report</li>
</ul>
<form id="product_list_form" action="" method="post" class="product_list">
    {% csrf_token %}
    <table class="product_list_table" style="width: auto">
        <tr>
            <th>id-2</th>
            <th>UPC</th>
            <th>Name</th>
            <th>Type</th>
            <th>Brand</th>
            <th>Weight(Kg)</th>
            <th>Description</th>
            <th>Total</th>
            <th>Last Update</th>
            <th>Is Active</th>
            <th>Modify/Delete</th>
        </tr>
        {% for obj in product_list %}
            {% with inventory_obj=inventory_list.obj.id %}
                <tr style="width: 1300px">
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.upc }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.product_type_id.name }}</td>
                    <td>{{ obj.brand_id.name }}</td>
                    <td>{{ obj.weight }}</td>
                    <td>{{ obj.description }}</td>
                    <td>{{ inventory_obj.total }}</td>
                    <td>{{ obj.update_at }}</td>
                    <td>{{ obj.is_active }}</td>
                    <td><a href="{% url 'inventory:product_edit' obj.id %}" class="btn btn-primary">Modify</a>
                        <a href="{% url 'inventory:product_delete' obj.id %}" class="btn btn-danger">/Delete</a>
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
    </table>
</form>
</body>
</html>